---
# ============================================================================
# SSH KEY COPY PLAYBOOK
# ============================================================================
# This playbook copies your SSH public key to all servers in the inventory.
#
# PREREQUISITES:
# 1. You must have password-based SSH access to the servers initially
# 2. Your SSH public key must exist at ~/.ssh/id_ed25519.pub
#
# USAGE:
# If you have password access, run:
#   ansible-playbook -i inventory.ini copy-ssh-key.yml --ask-pass --ask-become-pass
#
# If password authentication is disabled, you'll need to manually copy the key:
#   ssh-copy-id -i ~/.ssh/id_ed25519.pub mhadmin@<server-ip>
#
# ALTERNATIVE: Use the helper script:
#   ./scripts/copy-ssh-keys.sh
# ============================================================================

- name: Copy SSH public key to all servers
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Determine SSH public key path
      ansible.builtin.set_fact:
        ssh_key_path: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
      delegate_to: localhost
      become: false
      run_once: true

    - name: Read SSH public key from control node
      ansible.builtin.slurp:
        src: "{{ ssh_key_path }}"
      delegate_to: localhost
      become: false
      run_once: true
      register: ssh_key_file
      failed_when: false

    - name: Fail if SSH key file not found
      ansible.builtin.fail:
        msg: "SSH public key not found at {{ ssh_key_path }}. Please ensure the key exists on the control node."
      when: not ssh_key_file.content is defined
      run_once: true

    - name: Decode SSH public key content
      ansible.builtin.set_fact:
        ssh_public_key: "{{ ssh_key_file.content | b64decode }}"
      run_once: true
      when: ssh_key_file.content is defined

    - name: Ensure .ssh directory exists with correct permissions
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'
      when: ssh_public_key is defined

    - name: Copy public key to authorized_keys
      ansible.builtin.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ ssh_public_key }}"
        path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        manage_dir: false
      when: ssh_public_key is defined