---
- name: Copy SSH public key to all servers
  hosts: all
  become: true
  tasks:
    - name: Copy public key
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"