---
- name: Join nodes to Kubernetes cluster using kubeadm
  hosts: all:!control
  become: true
  gather_facts: true

  tasks:
    - name: Display join information
      ansible.builtin.debug:
        msg:
          - "======================================================"
          - "  Kubernetes Node Join (kubeadm join)"
          - "======================================================"
          - ""
          - "Target nodes: All nodes EXCEPT control plane"
          - "Control plane nodes will be joined manually"
          - ""
          - "Required variables:"
          - "  - join_token"
          - "  - discovery_token_ca_cert_hash"
          - "  - api_server_endpoint"
          - ""
          - "======================================================"
      run_once: true

    # =============================================================================
    # Auto-fetch join information (optional)
    # =============================================================================
    - name: Check if kubectl is available for auto-fetch
      ansible.builtin.command:
        cmd: which kubectl
      register: kubectl_check
      when: auto_fetch_join_info
      delegate_to: "{{ control_plane_host }}"
      changed_when: false
      failed_when: false
      run_once: true

    - name: Fetch join token from control plane
      ansible.builtin.shell: |
        kubeadm token list -o jsonpath='{.token}' | head -1
      register: fetched_token
      when: auto_fetch_join_info and kubectl_check.rc == 0
      delegate_to: "{{ control_plane_host }}"
      changed_when: false
      run_once: true

    - name: Fetch CA cert hash from control plane
      ansible.builtin.shell: |
        openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | \
        openssl rsa -pubin -outform der 2>/dev/null | \
        openssl dgst -sha256 -hex | sed 's/^.* //'
      register: fetched_ca_hash
      when: auto_fetch_join_info and kubectl_check.rc == 0
      delegate_to: "{{ control_plane_host }}"
      changed_when: false
      run_once: true

    - name: Set join token from fetched value
      ansible.builtin.set_fact:
        join_token: "{{ fetched_token.stdout }}"
      when: auto_fetch_join_info and fetched_token.stdout is defined and join_token == ""
      run_once: true

    - name: Set CA cert hash from fetched value
      ansible.builtin.set_fact:
        discovery_token_ca_cert_hash: "sha256:{{ fetched_ca_hash.stdout }}"
      when: auto_fetch_join_info and fetched_ca_hash.stdout is defined and discovery_token_ca_cert_hash == ""
      run_once: true

    - name: Display fetched join information
      ansible.builtin.debug:
        msg:
          - "Fetched join information:"
          - "  Token: {{ join_token[:10] }}... (truncated for security)"
          - "  CA Hash: {{ discovery_token_ca_cert_hash[:20] }}... (truncated)"
      when: auto_fetch_join_info and fetched_token.stdout is defined
      run_once: true

    - name: Validate required variables are set
      ansible.builtin.fail:
        msg: "{{ item }} is required. Set it via -e {{ item }}=value, enable auto_fetch_join_info=true, or set in the playbook vars."
      loop:
        - join_token
        - discovery_token_ca_cert_hash
        - api_server_endpoint
      when: (item == "" or item is not defined) and not (auto_fetch_join_info and item == "api_server_endpoint")
      run_once: true

    # =============================================================================
    # Pre-join checks
    # =============================================================================
    - name: Check if kubeadm is installed
      ansible.builtin.command:
        cmd: which kubeadm
      register: kubeadm_check
      changed_when: false
      failed_when: false

    - name: Fail if kubeadm is not installed
      ansible.builtin.fail:
        msg: "kubeadm is not installed on {{ inventory_hostname }}. Please install it first."
      when: kubeadm_check.rc != 0


    - name: Check if node is already part of the cluster
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_config
      failed_when: false

    - name: Skip if node is already joined
      ansible.builtin.debug:
        msg: "Node {{ inventory_hostname }} is already part of the cluster. Skipping join."
      when: skip_if_already_joined and kubelet_config.stat.exists
      changed_when: false

    - name: Check if containerd is running
      ansible.builtin.systemd:
        name: containerd
      register: containerd_status
      failed_when: false

    - name: Ensure containerd is running
      ansible.builtin.systemd:
        name: containerd
        state: started
        enabled: yes
      when: containerd_status.status.ActiveState != "active"

    # =============================================================================
    # Prepare join command
    # =============================================================================
    - name: Build base kubeadm join command
      ansible.builtin.set_fact:
        join_command: >
          kubeadm join {{ api_server_endpoint }}
          --token {{ join_token }}
          --discovery-token-ca-cert-hash {{ discovery_token_ca_cert_hash }}
          --ignore-preflight-errors=all

    - name: Add node labels to join command
      ansible.builtin.set_fact:
        join_command: "{{ join_command }} --node-labels={{ node_labels | join(',') }}"
      when: node_labels | length > 0

    - name: Add node taints to join command
      ansible.builtin.set_fact:
        join_command: "{{ join_command }} --node-taints={{ node_taints | join(',') }}"
      when: node_taints | length > 0

    # =============================================================================
    # Execute kubeadm join
    # =============================================================================
    - name: Display join command (without token for security)
      ansible.builtin.debug:
        msg: "Joining node {{ inventory_hostname }} to cluster at {{ api_server_endpoint }}"
      when: not (skip_if_already_joined and kubelet_config.stat.exists)

    - name: Execute kubeadm join
      ansible.builtin.shell: "{{ join_command }}"
      register: join_result
      when: not (skip_if_already_joined and kubelet_config.stat.exists)

    - name: Display join result
      ansible.builtin.debug:
        msg: "{{ join_result.stdout_lines }}"
      when: not (skip_if_already_joined and kubelet_config.stat.exists) and join_result.stdout_lines is defined

    # =============================================================================
    # Post-join configuration
    # =============================================================================
    - name: Wait for kubelet to be ready
      ansible.builtin.systemd:
        name: kubelet
        state: started
      register: kubelet_status
      until: kubelet_status.status.ActiveState == "active"
      retries: 30
      delay: 2
      when: not (skip_if_already_joined and kubelet_config.stat.exists)

    - name: Enable kubelet service
      ansible.builtin.systemd:
        name: kubelet
        enabled: yes
      when: not (skip_if_already_joined and kubelet_config.stat.exists)

    - name: Wait for node to appear in cluster (up to 2 minutes)
      ansible.builtin.pause:
        seconds: 10
      when: not (skip_if_already_joined and kubelet_config.stat.exists)
      delegate_to: localhost
      run_once: true

    # =============================================================================
    # Verification
    # =============================================================================
    - name: Check kubelet service status
      ansible.builtin.systemd:
        name: kubelet
      register: final_kubelet_status
      changed_when: false

    - name: Check if node config exists
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: final_kubelet_config
      changed_when: false

    - name: Display join summary
      ansible.builtin.debug:
        msg:
          - "======================================================"
          - "Node {{ inventory_hostname }} join status:"
          - "  Kubelet service: {{ final_kubelet_status.status.ActiveState }}"
          - "  Kubelet config: {{ 'Present' if final_kubelet_config.stat.exists else 'Missing' }}"
          - "  Status: {{ 'SUCCESS' if final_kubelet_config.stat.exists and final_kubelet_status.status.ActiveState == 'active' else 'CHECK REQUIRED' }}"
          - "======================================================"
